name: build-vsix

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Linux deps
      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 make g++ libssl-dev

      # macOS deps
      - name: Install macOS deps
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install openssl@3
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV

      # Windows deps
      - name: Install Windows deps (OpenSSL via vcpkg)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install openssl:x64-windows
          echo "OPENSSL_INCLUDE_DIR=$pwd\vcpkg\installed\x64-windows\include" >> $env:GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$pwd\vcpkg\installed\x64-windows\lib" >> $env:GITHUB_ENV

      - name: Install npm deps
        run: npm ci

      - name: Compile TS
        run: npm run compile

      - name: Build native
        run: npm run build:native

      - name: Package VSIX
        run: |
          node -e "require('fs').mkdirSync('dist-vsix',{recursive:true})"
          npx vsce package -o dist-vsix/idyicyanere-${{ runner.os }}.vsix

      - uses: actions/upload-artifact@v4
        with:
          name: vsix-${{ runner.os }}
          path: dist-vsix/*.vsix
