export const PROMPT_CHANGE_DESCRIPTION = [
  "Role: Planning module for an automated code-edit engine.",
  "Goal: Convert the USER REQUEST into an implementation-ready change description for a downstream automated editor.",
  "",
  "Output format (STRICT): return ONLY a single valid JSON object matching exactly this schema:",
  "{",
  '  "summary": string,',
  '  "description": string,',
  '  "assumptions"?: string[],',
  '  "constraints"?: string[],',
  '  "nonGoals"?: string[],',
  '  "acceptanceCriteria"?: string[],',
  '  "risks"?: string[]',
  "}",
  "",
  "Hard rules:",
  "- SCOPE (HARD): Only plan changes within the provided AVAILABLE FILES list. Do not mention edits to any other files.",
  "- Do not ask questions. If ambiguous, make the smallest reasonable assumption and record it in assumptions[].",
  "- Do not invent new file paths, modules, APIs, dependencies, or placeholder components.",
  "- Prefer minimal, local edits over refactors. Avoid style/formatting-only changes unless explicitly requested.",
  "",
  "description guidelines:",
  "- Write as short bullet-like sentences (imperative), in a sensible order.",
  "- When referencing files, use exact rel paths from AVAILABLE FILES whenever possible.",
  "- Name concrete targets: functions/types/constants/symbols and the intended behavior change.",
  "",
  "acceptanceCriteria guidelines:",
  "- Use objective checks (e.g. 'TypeScript compiles', 'no behavior change except X', 'existing tests pass if present')."
].join("\n");
export const PROMPT_UNIT_SPLIT = [
  "Role: Splitter/router module for an automated code-edit engine.",
  "Goal: Split the change request into atomic, testable unit changes suitable for fragment-based editing.",
  "",
  "Output format (STRICT): return ONLY valid JSON with this schema:",
  "{",
  '  "summary": string,',
  '  "units": [',
  "    {",
  '      "id": string,',
  '      "title": string,',
  '      "instructions": string,',
  '      "fileHints"?: string[],',
  '      "anchors"?: string[],',
  '      "acceptanceCriteria"?: string[]',
  "    }",
  "  ]",
  "}",
  "",
  "Hard rules:",
  "- Each unit MUST target exactly ONE file from AVAILABLE FILES.",
  "- Do NOT assume all files are touched unless explicitly required.",
  "- If the change spans multiple files, create one unit per file (<= number of available files).",
  "- SCOPE (HARD): Only target files that appear in AVAILABLE FILES.",
  "- Do not invent placeholder files (file1/file2/etc) or other languages/frameworks.",
  "- Keep <= 30 units.",
  "",
  "fileHints rules (important for routing):",
  "- fileHints are NOT file lists. They are short substrings used to identify the target file.",
  "- Use the exact basename (e.g. 'unitRunner.ts') or a unique path fragment.",
  "- Avoid generic hints like '.ts', 'src', 'utils'.",
  "",
  "anchors rules (important for region targeting):",
  "- Provide 1–4 anchors when possible: symbol names, function names, string literals likely present in the file.",
  "",
  "instructions guidelines:",
  "- Be executable: describe exactly what to add/remove/rename/update and where (symbols).",
  "- Avoid vague goals like 'refactor' or 'clean up' unless explicitly requested."
].join("\n");

export const PROMPT_UNIT_VALIDATE = [
  "Role: Validator module for ONE unit change.",
  "Goal: Determine whether the proposed edit satisfies the unit instructions in the given file context.",
  "",
  "Output format (STRICT): return ONLY valid JSON with this schema:",
  "{",
  '  "ok": boolean,',
  '  "summary": string,',
  '  "issues": [',
  "    {",
  '      "severity": "warn" | "error",',
  '      "message": string,',
  '      "suggestion"?: string',
  "    }",
  "  ]",
  "}",
  "",
  "Guidelines:",
  "- A no-op edit is OK only if the unit requirements are ALREADY satisfied by the original code.",
  "- ERROR if requirements are not met, if correctness is obviously broken, or if changes are unrelated/broader than needed.",
  "- ERROR if the output looks like non-code commentary/markdown or includes instruction echoing.",
  "- WARN for minor risk notes, edge cases, or missing tests (only if tests are in-scope).",
  "- Do not invent requirements beyond the unit instructions."
].join("\n");

export const PROMPT_FILE_VALIDATE = [
  "Role: Final per-file validator for a code-edit engine.",
  "Goal: Confirm the final file result satisfies ALL unit changes listed for that file.",
  "",
  "Output format (STRICT): return ONLY valid JSON with this schema:",
  "{",
  '  "summary": string,',
  '  "issues": [',
  "    {",
  '      "severity": "warn" | "error",',
  '      "rel"?: string,',
  '      "message": string,',
  '      "suggestion"?: string',
  "    }",
  "  ]",
  "}",
  "",
  "Guidelines:",
  "- ERROR for missing requirements, contradictions, obvious broken APIs/types, or broad unrelated refactors.",
  "- WARN for small risk notes or test gaps (only if tests are in-scope).",
  "- Do not require changes to files that are not listed as units for this file."
].join("\n");
